baseurl = "https://pietromaggi.com/"
languageCode = "en-us"
metaDataFormat = "toml"
# theme = "beautifulhugo"
theme = "hugo-tufte"
# title = "Pietro . Maggi"
title = "Garbage Collector"
paginate = 10
enableRobotsTXT = true
#
# pygmentsUseClasses=true
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true
#     # pygmentsStyle = "docco"
#     # pygmentsUseClasses = true
#     # pygmentsCodeFences = true
#     # pygmentsCodefencesGuessSyntax = true
# pygmentOptions = "linenos=inline"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
  # Add meta keywords in head part (Site Keywords or Tags of Page)
  keywords = ["Pietro F. Maggi","android","jetpack","kotlin"]
	# Add meta description in head part
	description = "Pietro F. Maggi - Personal Website/Blog"
	# Add a subtitle to your website
	subtitle = "tales from an old nibble"
	# Activate to show authors on pages if available
	hideAuthor = true
	# Add math typesetting with KaTeX (Global with this Param)
	math = false

  since = "2013"
  showLicense = true
  License = '<a href="/privacy_policy">Privacy Policy</a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>'

  name = "Pietro F. Maggi"
  email = "blog@pietromaggi.com"
  github = "pfmaggi"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "pfmaggi"
  #reddit = "username"
  linkedin = "pietromaggi"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  mastodon = "https://androiddev.social/@pfmaggi"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

  # Optional 80x80 avatar image.
	logo = "images/pfm.png"
  favicon = "favicon/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  socialShare = false
  showRelatedPosts = true
  enableEmoji = true
  # Your name or the name of you company
  copyrightHolder = "Copyright Pietro F. Maggi"
  # Show the "Powered by Hugo-Tufte and Hugo."
  showPoweredBy = true
  # Site wide kill switch
  hidedate = false
  # Uncomment for dark code blocks
  # codeBlocksDark = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    # style = "monokailight"
    style = "solarized-light"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
#       hardWraps = false
      unsafe = true
#       xhtml = false

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

pygmentsUseClasses = true
canonifyurls = true
# Nav.
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

# [[menu.main]]
# name = "About"
# url = "/page/about"
# weight = 2

# [[menu.main]]
# name = "Talks"
# url = "/page/talks"
# weight = 3

[[menu.nav]]
  name = "Home"
  pre = "<i class='fas fa-home la-lg'></i>"
  weight = -110
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fas fa-book fa-lg'></i> "
  weight = -100
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fas fa-tags fa-lg'></i> "
  weight = -90
  identifier = "categories"
  url = "/categories"
[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-info-circle  fa-lg'></i> "
  weight = -80
  identifier = "about"
  url = "/page/about"
[[menu.nav]]
  name = "Talks"
  pre = "<i class='fab fa-github fa-lg'></i> "
  weight = -70
  identifier = "talks"
  url = "/page/talks"

# -----------------------------------------------------------------------
# FOOTER MENU
# If you need to add custom links to you footer: put them here. Be aware that this theme is using fontawesome.
# Please head to https://fontawesome.com/v4.7/icons/ to pick icons
# -----------------------------------------------------------------------

# [[menu.footer]]
#   name = "Custom footer link"
#   pre = "<i class='fab fa-google fa-lg'></i> "
#   weight = -90
#   identifier = "custom_link"
#   url = "https://google.com"
