baseurl = "https://pietromaggi.com/"
languageCode = "en-EN"
metaDataFormat = "toml"
theme = "beautifulhugo"
paginate = 10
enableRobotsTXT = true
#
# pygmentsUseClasses=true
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true
#     # pygmentsStyle = "docco"
#     # pygmentsUseClasses = true
#     # pygmentsCodeFences = true
#     # pygmentsCodefencesGuessSyntax = true
# pygmentOptions = "linenos=inline"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[author]
  name = "Pietro F. Maggi"
  email = "blog@pietromaggi.com"
  github = "pfmaggi"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "pfmaggi"
  #reddit = "username"
  linkedin = "pietromaggi"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[Params]
  # Add meta keywords in head part (Site Keywords or Tags of Page)
  keywords = ["Pietro F. Maggi","android","jetpack","kotlin"]
	# Add meta description in head part
	description = "Pietro F. Maggi - Personal Website/Blog"
	# Add pagetitle to homepage <title> tag
	hometitle = "Garbage Collector"
	# Add a subtitle to your website
	subtitle = "Tales from an old nibble"
	# Activate to show authors on pages if available
	hideAuthor = true
	# Add math typesetting with KaTeX (Global with this Param)
	math = false

  since = "2013"
  showLicense = true
  License = '<a href="/privacy_policy">Privacy Policy</a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>'
	
  # Optional 80x80 avatar image.
	logo = "images/pfm.png"
  favicon = "images/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  socialShare = false
  showRelatedPosts = true
  enableEmoji = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    # style = "monokailight"
    style = "solarized-light"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
#     [markup.goldmark.renderer]
#       hardWraps = false
#       unsafe = false
#       xhtml = false

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/page/about"
weight = 2

[[menu.main]]
name = "Talks"
url = "/page/talks"
weight = 3

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/pfmaggi"

[markup.goldmark.renderer]
unsafe = true
